---
version: "2.1"
services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      #- JELLYFIN_PublishedServerUrl=192.168.0.5 #optional
    volumes:
      - ${JELLYFIN_CONFIG}:/config
      - ${JELLYFIN_TVSHOWS}:/data/tvshows
      - ${JELLYFIN_MOVIES}:/data/movies
      - ${JELLYFIN_TERROR_SERIES}:/data/terror_series
      - ${JELLYFIN_TERROR_MOVIES}:/data/terror_movies
      - ${JELLYFIN_FAMILY_MOVIES}:/data/family_movies
      - ${JELLYFIN_SECOND_HDD}:/data/data2
    ports:
      - 8096:8096
      - 8920:8920 #optional
      - 7359:7359/udp #optional
      - 1900:1900/udp #optional
    restart: always
    
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${RADARR_CONFIG}:/config
      - ${RADARR_MOVIES}:/movies #optional
      - ${RADARR_DOWNLOADS}:/downloads #optional
    ports:
      - 7878:7878
    restart: unless-stopped
    
  transmission:
    image : jaymoulin/transmission
    command: transmission-daemon -f -g /config
    environment:
      - TZ=Europe/Madrid
    volumes:
      - ${TRANSMISSION_CONFIG}:/config
      - ${TRANSMISSION_DOWNLOADS}:/root/Downloads
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    expose:
      - 9091
    restart: unless-stopped

  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: jackett
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
      - AUTO_UPDATE=true #optional
      #- RUN_OPTS=<run options here> #optional
    volumes:
      - ${JACKETT_CONFIG}:/config
      - ${JACKETT_DOWNLOADS}:/downloads
    ports:
      - 9117:9117
    restart: unless-stopped
    
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Madrid
    volumes:
      - ${SONARR_CONFIG}:/config
      - ${SONARR_TVSHOWS}:/tv #optional
      - ${SONARR_DOWNLOADS}:/downloads #optional
    ports:
      - 8989:8989
    restart: unless-stopped
